### ISSUE TITLE
Improve error messages thrown by runtimes

### ISSUE THREAD

**Issue by dvilchez** [reTHINK-project/dev-hyperty#32]
Add better description and a way to address the solution.

For example, this error:

![e3253c8a-3252-11e6-8d79-d90d1fab7ad7](https://cloud.githubusercontent.com/assets/153025/16074574/5f2f1290-32eb-11e6-80e7-34e9438649c5.png)

actually is hiding an error on Identity Module
<img width="633" alt="screen-shot-2016-06-15-11-18-39" src="https://cloud.githubusercontent.com/assets/153025/16074629/add514b2-32eb-11e6-9fdf-0a894db6ea69.png">

**Comment by pchainho** [comment]
done
