### ISSUE TITLE
Development of hyperties per branch

### ISSUE THREAD

**Issue by vitormsilva** [reTHINK-project/dev-hyperty#33]
To distinguish the development status of hyperties we suggest to only have in the master branch Hyperties that are stable enough to be deployed in the testbeds and published in the catalogue. Then the development of Hyperties would be done on separated branch each one having a reduced number of hyperties on src folder. For this development branches we have two suggestions:
- have a branch for each partner containing in the src folder only hyperties developed by the partner.
- have a branch for each hyperty, where for each hyperty we could do a release of that hyperty and merge in the master branch.

Other suggestions are welcome

**Comment by Endebert** [comment]
If you have a branch that has all hyperties and their handlebars deleted except one, and then merge that branch into the master branch, you would also automatically remove those hyperties and their handlebars from the master branch (unless there is a conflict). So I don't know if that would be a viable approach.
