### ISSUE TITLE
reTHINK-DT-HfTL-CallCenter Hyperty

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-hyperty#34]
Currently, it seems there is some ICE related issue that prevents interoperability between this Hyperty running in "https://dev.rethink.tlabscloud.com/" domain and the ALB Connector Hyperty running in the "https://hybroker.rethink.ptinovacao.pt/examples/" domain.

There are NO errors in the console but ICE candidates are exchanged and none works. I've changed the STUN/TURN configuration to be the same as the one used by our Connector but it didn't improve.

Interoperability between "rethink.tlabscloud.com" and "hybroker.rethink.ptinovacao.pt" with Connector Hyperty works fine.

**Comment by sdruesedow** [comment]
I think this one is resolved.
