### ISSUE TITLE
Update your hyperties - HypertyDiscovery is deprecated

### ISSUE THREAD

**Issue by vitormsilva** [reTHINK-project/dev-hyperty#36]
The HypertyDiscovery in service-framework develop branch, is deprecated and will be removed soon on release.

Please, update your hyperties;

See [issue 55](https://github.com/reTHINK-project/dev-service-framework/issues/55)

**Comment by pchainho** [comment]
At least the following Hyperties must be updated:

* "NotificationsReporter" @dvilchez 
* "SurveyObserver" @dvilchez 
* "SurveyReporter" @dvilchez 
* "user-status" @NicoApizee
