### ISSUE TITLE
Group Chat (Quobis) not Working at Hybroker testbed but Works at Quobis Testbed

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-hyperty#42]
I suspect this is because the most updated version was not published to the default catalogue. Can you check pls?

At both Testbeds, sent messages are not displayed.

**Comment by dvilchez** [comment]
I've just updated it in defualt catalogue

**Comment by dvilchez** [comment]
Can we close this @pchainho?

**Comment by pchainho** [comment]
yes
