### ISSUE TITLE
Group Chat update

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-hyperty#46]
Update according to most [updated communication data model spec](https://github.com/reTHINK-project/specs/tree/master/datamodel/data-objects/communication)

**Comment by dvilchez** [comment]
@pchainho it looks like authorise function in  synchermanger expects an array of hypertyurl and not an object in which each key is a hypertyurl as is described in the new communication scheme
<img width="669" alt="screen-shot-2017-03-13-17-16-02" src="https://cloud.githubusercontent.com/assets/153025/23865211/41c65934-0815-11e7-95e8-ce48cdd2f9e5.png">
