### ISSUE TITLE
Unable to send message from one hyperty to another

### ISSUE THREAD

**Issue by Endebert** [reTHINK-project/dev-hyperty#57]
Our RoomClient hyperty is not able to send a message to the RoomServer hyperty directly anymore.

This is the order of events happening:
1. RoomServer hyperty is started with identity `openidtest10@gmail.com`
2. RoomClient hyperty is started with any identity
3. RoomClient discovers RoomServer hyperty URL using discovery
4. RoomClient sends 'execute' message to RoomServer hyperty URL in this manner: 
    ```
    // create execute message
    let msg = {
        type: 'execute', from: this.hypertyURL, to: remoteHypertyURL,
        body: {method: method, params: params}
    };
    // send message, resolve on reply
    this.bus.postMessage(msg, (reply) => {
        l.d("got " + method + " reply!", reply);
        if (reply.body.code == 200) {
            let urls = reply.body.value;
            resolve(urls);
        } else {
            l.e("execute request rejected (" + reply.body.code + "):", reply.body.value);
            reject(reply.body.value);
        }
    });
    ```
5. RoomClient receives generic 408 response timeout

This procedure worked in the past. I don't know if I'm missing something in the message, or if there is some other problem. The error message doesn't help much unfortunately.

It is very urgent that we solve this issue, since the hotel room demo depends on it.

I've modified the RoomServer and RoomClient hyperties, they should work in the toolkit out-of-the-box, so that you can test it yourself. Only important step is that __RoomServer hyperty must be run with identity "openidtest10@gmail.com"__, and the RoomServer hyperty has to be started before the RoomClient hyperty.

@pchainho @vitormsilva @dvilchez @jboulmal anyone knows how to solve this issue?

**Comment by pchainho** [comment]
I suspect the Policy Engine is blocking this message: Can you try another message type eg read?

Pls also provide the logs

**Comment by Endebert** [comment]
Here are the logs:

[toolkit_roomclient.txt](https://github.com/reTHINK-project/dev-hyperty/files/1063999/toolkit_roomclient.txt)
[toolkit_roomserver.txt](https://github.com/reTHINK-project/dev-hyperty/files/1064000/toolkit_roomserver.txt)

I've tried changing the message type to read, but it results in the same error.

We've noticed that this problem does not occur when running the roomserver in the nodejs runtime. Since nodejs uses a static identity, I'm assuming the problem must be identity related.
