### ISSUE TITLE
Wallet Hyperty implementation

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-hyperty#83]
see [spec](https://github.com/reTHINK-project/dev-hyperty/blob/develop/docs/_hyperties/Wallet-Hyperty.md)

- [x] collect and send user data,

**Comment by pchainho** [comment]
Missing Wallet Reporter creation at Vertx p2p Stub with new [Wallet Manager](https://github.com/reTHINK-project/dev-service-framework/issues/138) lib

**Comment by Felgueiras** [comment]
- [ ] fetch current identity
- [ ] send transactions back to UI

**Comment by pchainho** [comment]
- [ ] use User GUID instead of User URL
